# Generated by Django 5.0.3 on 2024-03-21 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('Montant', models.FloatField()),
                ('disponible', models.BooleanField(default=True)),
                ('pourcentage', models.FloatField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='imagesMessages')),
                ('contenu', models.TextField()),
                ('NomAuteur', models.CharField(default='SMARTINVEST', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('Motif', models.TextField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('Numero', models.CharField(blank=True, max_length=13, null=True)),
                ('PorteFeuille', models.CharField(blank=True, max_length=100, null=True)),
                ('Montant', models.FloatField()),
                ('MontantUSDT', models.FloatField(blank=True, null=True)),
                ('Type', models.CharField(max_length=10)),
                ('valide', models.BooleanField(default=False)),
                ('en_attente', models.BooleanField(default=False)),
                ('Auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
