# Generated by Django 5.0.3 on 2024-03-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartInvestApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='pourcentage',
            field=models.FloatField(default=2),
        ),
    ]
