# Generated by Django 5.0.3 on 2024-03-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartInvestApp', '0002_alter_contrat_pourcentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OM', models.CharField(blank=True, max_length=13, null=True)),
                ('MTN', models.CharField(blank=True, max_length=13, null=True)),
                ('BEP20', models.CharField(blank=True, max_length=130, null=True)),
                ('ERC20', models.CharField(blank=True, max_length=130, null=True)),
                ('TRC20', models.CharField(blank=True, max_length=130, null=True)),
            ],
        ),
    ]
