# Generated by Django 5.0.3 on 2024-03-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartInvestApp', '0003_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='contrat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
