# Generated by Django 5.0.3 on 2024-03-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartInvestApp', '0005_alter_transaction_en_attente'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='prixUSDT',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
