# Generated by Django 5.0.3 on 2024-03-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartInvestApp', '0007_alter_information_prixusdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='nomMTN',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='nomOM',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='OM',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
