# Generated by Django 5.0.3 on 2024-03-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartInvestApp', '0008_information_nommtn_information_nomom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='pourcentage',
            field=models.FloatField(default=3.5),
        ),
    ]
