# Generated by Django 5.0.3 on 2024-03-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComptesSmart', '0003_alter_utilisateur_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone2',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
