# Generated by Django 5.0.3 on 2024-03-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComptesSmart', '0004_alter_utilisateur_email_alter_utilisateur_telephone2'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
