# Generated by Django 5.0.3 on 2024-03-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComptesSmart', '0005_utilisateur_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='date_contrat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='historique_solde',
            field=models.TextField(default=''),
        ),
    ]
