# Generated by Django 5.0.3 on 2024-03-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComptesSmart', '0006_utilisateur_date_contrat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='contrat_expire',
            field=models.BooleanField(default=False),
        ),
    ]
